import { existsSync, mkdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { OMO_SCI_VERSION } from './install-manifest';

export const RUNTIME_PLUGIN_DIR = 'plugins';
export const RUNTIME_PLUGIN_FILE = 'omo-sci.js';
export const RUNTIME_PLUGIN_MARKER = 'omo-sci-runtime-plugin';

export function runtimePluginPath(projectDir: string): string {
  return join(resolve(projectDir), '.opencode', RUNTIME_PLUGIN_DIR, RUNTIME_PLUGIN_FILE);
}

export async function writeRuntimePlugin(projectDir: string): Promise<string> {
  const outputPath = runtimePluginPath(projectDir);
  mkdirSync(join(resolve(projectDir), '.opencode', RUNTIME_PLUGIN_DIR), { recursive: true });
  const result = await Bun.build({
    entrypoints: [join(import.meta.dir, 'runtime-entry.ts')],
    target: 'bun',
    format: 'esm',
    minify: false,
    sourcemap: 'none',
  });

  if (!result.success || result.outputs.length !== 1) {
    const details = result.logs.map(log => String(log)).join('\n');
    throw new Error(`无法生成 OpenCode 运行时插件${details ? `:\n${details}` : ''}`);
  }

  const bundled = await result.outputs[0]!.text();
  const header = [
    `// ${RUNTIME_PLUGIN_MARKER}`,
    `// package-version: ${OMO_SCI_VERSION}`,
    '// Generated by `omo-sci install`; do not edit by hand.',
    '',
  ].join('\n');
  await Bun.write(outputPath, `${header}${bundled}`);
  return outputPath;
}

export function checkRuntimePlugin(projectDir: string): {
  exists: boolean;
  version: string | null;
  valid: boolean;
  path: string;
} {
  const path = runtimePluginPath(projectDir);
  if (!existsSync(path)) return { exists: false, version: null, valid: false, path };

  const prefix = readFileSync(path, 'utf8').slice(0, 512);
  const version = prefix.match(/^\/\/ package-version: (.+)$/m)?.[1]?.trim() ?? null;
  return {
    exists: true,
    version,
    valid: prefix.includes(RUNTIME_PLUGIN_MARKER) && version === OMO_SCI_VERSION,
    path,
  };
}
